#!/bin/sh

if [ -f /usr/local/bin/brew ] ; then
	echo 'Homebrew is already installed!!'
	echo 'To reinstall, first remove the previous install, then run this installer again.'
	echo 'To COMPLETELY remove Homebrew AND everything it installed use this script:'
	echo '    https://gist.github.com/mxcl/1173223'
	echo
	exit 1
fi

if [ `sw_vers -productVersion | tr -d '.'` -le '1058' ] ; then
	echo '##########################################################'
	echo '    Attempting to install Tigerbrew for Tiger/Leopard.....'
	echo '##########################################################'
	echo ''
	ruby -e "$(curl -fsSkL raw.github.com/mistydemeo/tigerbrew/go)"
	echo
else
	echo '##########################################################'
	echo '    Attempting to install Homebrew for Snow Leopard + ....'
	echo '##########################################################'
	echo ''
	ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
	echo 
fi

if [ $? = 0 ] ; then
	OUTCOME='Succeeded!!!'
	echo '##########################################################'
	echo '    Attempt to install Homebrew $OUTCOME...'
	echo '##########################################################'
	echo
else
	OUTCOME='FAILED, Try Again...'
	echo '##########################################################'
	echo '    Attempt to install Homebrew $OUTCOME...'
	echo '==> To COMPLETELY remove Homebrew AND everything it installed use this script:'
	echo '    https://gist.github.com/mxcl/1173223'
	echo '##########################################################'
	echo
	exit 1
fi

if [ -f `which brew` ] ; then
	echo '/usr/local/bin is allready in your PATH.... Calling brew to finish the install..'
	echo	
else
	echo 'Brew is not in your PATH. This script will add it for you.'
	echo
	echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bashrc
	if [ $? != 0 ] ; then
		echo '  ==> Failed to permanently add /usr/local/bin to your system path...'
		echo '  ==> Please manually edit the file /home/$USER/.bashrc and add the following line:'
		echo '    export PATH="/usr/local/bin:$PATH"'
		PATH="/usr/local/bin:$PATH"
		echo 'Temporarily added: /usr/local/bin to your PATH. Calling brew to finish the install.'
		echo
	fi
fi

	echo '##########################################################'
	echo '==> Check the following output for potential problems!'
	echo '	You may want to fix these first! (Just copy the commands brew suggests...)'
	echo '==> Run `brew doctor` to check if all warnings have been fixed'
	echo '  Once everything is in place run `brew update` to sync the latest Homebrew application catalogs.'
	echo '==> Type `brew help` or `man brew` to find out how to use Homebrew.'
	echo '##########################################################'
	echo

	brew doctor

	echo
	echo '##### End Homebrew / Tigerbrew autoinstaller. You are on your own again! #####'
	echo '         Installer By: Arjan van Lent - Codejugglers 2013'
	echo '                  *** http://codejugglers.nl ***'
	echo
	
exit 0
